name: flora
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
 
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  beautiful_soup_dart: ^0.3.0
  path: ^1.8.3
  http_parser: ^4.0.2
  google_fonts: ^6.0.0
  google_nav_bar: ^5.0.6
  webview_flutter: ^4.4.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.13.6
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  file_picker: ^6.0.0
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  url_launcher: ^6.1.14
  intl_phone_number_input: ^0.7.3+1
  camera: ^0.10.5+5
  camera_web: ^0.3.2+2
  http: ^1.1.0
  provider: ^6.0.5
  super_rich_text: ^1.0.0
  photo_view: ^0.14.0
  weather: ^3.1.1
  responsive_sizer: ^3.2.0
  speech_to_text: ^6.3.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - lib/images/
    - lib/assets/
  fonts: 
    - family: Dosis
      fonts: 
        - asset: assets/fonts/DosisMedium.ttf
          weight: 500
        - asset: assets/fonts/DosisSemiBold.ttf
          weight: 600
        - asset: assets/fonts/DosisLight.ttf
          weight: 300
        - asset: assets/fonts/DosisRegular.ttf
          weight: 400
        - asset: assets/fonts/DosisBold.ttf
          weight: 700
    - family: Green Garden
      fonts: 
        - asset: assets/fonts/GreenGardenRegular.ttf
          weight: 400
    - family: SF Pro
      fonts: 
        - asset: assets/fonts/SFProRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
