// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94_nhcnoXgo7M0m08npwWJHD2Z2un8do',
    appId: '1:1021703972271:web:f6a733ed8bb5c70d063b5a',
    messagingSenderId: '1021703972271',
    projectId: 'flora-v1-99c35',
    authDomain: 'flora-v1-99c35.firebaseapp.com',
    storageBucket: 'flora-v1-99c35.appspot.com',
    measurementId: 'G-SYZST3V2RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM_KgWSUHiulFZv-hiKIqOOqtYh3bj_Ow',
    appId: '1:1021703972271:android:4d0b235025d71201063b5a',
    messagingSenderId: '1021703972271',
    projectId: 'flora-v1-99c35',
    storageBucket: 'flora-v1-99c35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_VT-JP8GSXdtsCFPWNEdaIqxJLZJOFI',
    appId: '1:1021703972271:ios:b068a59966d52196063b5a',
    messagingSenderId: '1021703972271',
    projectId: 'flora-v1-99c35',
    storageBucket: 'flora-v1-99c35.appspot.com',
    iosBundleId: 'com.flora.app',
  );
}
